language: python
python:
  - "2,6"
  - "2.7"
install: 
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -r test-requirements.txt --use-mirrors"
before_script:
  - cp gunclub/gunclub/development_settings.py.example gunclub/gunclub/development_settings.py
script:
  - python manager.py test 
notifications:
  irc:
    channels: "irc.freenode.org#gunclub"
    on_success: change
    on_failure: change
